language: node_js

node_js:
  - "6.5"

# after_success:
#  - scripts/deploy.sh

script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./scripts/compile.sh; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/deploy.sh; fi'